//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortalMVCApplication
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class JobSearchMvcEntities : DbContext
    {
        public JobSearchMvcEntities()
            : base("name=JobSearchMvcEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_AppliedJob> tbl_AppliedJob { get; set; }
        public virtual DbSet<tbl_Company> tbl_Company { get; set; }
        public virtual DbSet<tbl_Job> tbl_Job { get; set; }
        public virtual DbSet<tbl_JobSeeker> tbl_JobSeeker { get; set; }
        public virtual DbSet<tbl_Login> tbl_Login { get; set; }
    
        public virtual ObjectResult<Nullable<int>> sp_CountLoginId(string una, string pass)
        {
            var unaParameter = una != null ?
                new ObjectParameter("una", una) :
                new ObjectParameter("una", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_CountLoginId", unaParameter, passParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_GetLoginId(string una, string pass)
        {
            var unaParameter = una != null ?
                new ObjectParameter("una", una) :
                new ObjectParameter("una", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_GetLoginId", unaParameter, passParameter);
        }
    
        public virtual int sp_InsertJobApplication(Nullable<int> jid, Nullable<int> uid, string resume, string applyDate, string status)
        {
            var jidParameter = jid.HasValue ?
                new ObjectParameter("Jid", jid) :
                new ObjectParameter("Jid", typeof(int));
    
            var uidParameter = uid.HasValue ?
                new ObjectParameter("Uid", uid) :
                new ObjectParameter("Uid", typeof(int));
    
            var resumeParameter = resume != null ?
                new ObjectParameter("resume", resume) :
                new ObjectParameter("resume", typeof(string));
    
            var applyDateParameter = applyDate != null ?
                new ObjectParameter("applyDate", applyDate) :
                new ObjectParameter("applyDate", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertJobApplication", jidParameter, uidParameter, resumeParameter, applyDateParameter, statusParameter);
        }
    
        public virtual int sp_InsertJobOpenings(Nullable<int> cid, string jobTitle, string jobDes, string skill, string exp, string sal, string loc, string jobStatus, string lastDate, string postedDate)
        {
            var cidParameter = cid.HasValue ?
                new ObjectParameter("Cid", cid) :
                new ObjectParameter("Cid", typeof(int));
    
            var jobTitleParameter = jobTitle != null ?
                new ObjectParameter("jobTitle", jobTitle) :
                new ObjectParameter("jobTitle", typeof(string));
    
            var jobDesParameter = jobDes != null ?
                new ObjectParameter("jobDes", jobDes) :
                new ObjectParameter("jobDes", typeof(string));
    
            var skillParameter = skill != null ?
                new ObjectParameter("skill", skill) :
                new ObjectParameter("skill", typeof(string));
    
            var expParameter = exp != null ?
                new ObjectParameter("exp", exp) :
                new ObjectParameter("exp", typeof(string));
    
            var salParameter = sal != null ?
                new ObjectParameter("sal", sal) :
                new ObjectParameter("sal", typeof(string));
    
            var locParameter = loc != null ?
                new ObjectParameter("loc", loc) :
                new ObjectParameter("loc", typeof(string));
    
            var jobStatusParameter = jobStatus != null ?
                new ObjectParameter("jobStatus", jobStatus) :
                new ObjectParameter("jobStatus", typeof(string));
    
            var lastDateParameter = lastDate != null ?
                new ObjectParameter("lastDate", lastDate) :
                new ObjectParameter("lastDate", typeof(string));
    
            var postedDateParameter = postedDate != null ?
                new ObjectParameter("postedDate", postedDate) :
                new ObjectParameter("postedDate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertJobOpenings", cidParameter, jobTitleParameter, jobDesParameter, skillParameter, expParameter, salParameter, locParameter, jobStatusParameter, lastDateParameter, postedDateParameter);
        }
    
        public virtual int sp_InsertLoginCredentials(Nullable<int> id, string una, string pwd, string utype)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var unaParameter = una != null ?
                new ObjectParameter("una", una) :
                new ObjectParameter("una", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            var utypeParameter = utype != null ?
                new ObjectParameter("utype", utype) :
                new ObjectParameter("utype", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertLoginCredentials", idParameter, unaParameter, pwdParameter, utypeParameter);
        }
    
        public virtual ObjectResult<string> sp_LoginType(string una, string pass)
        {
            var unaParameter = una != null ?
                new ObjectParameter("una", una) :
                new ObjectParameter("una", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_LoginType", unaParameter, passParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_MaxLoginId()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_MaxLoginId");
        }
    
        public virtual int sp_RegisterCompany(Nullable<int> id, string na, string add, string email, string phone, string website, string photo)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var naParameter = na != null ?
                new ObjectParameter("na", na) :
                new ObjectParameter("na", typeof(string));
    
            var addParameter = add != null ?
                new ObjectParameter("add", add) :
                new ObjectParameter("add", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("Phone", phone) :
                new ObjectParameter("Phone", typeof(string));
    
            var websiteParameter = website != null ?
                new ObjectParameter("website", website) :
                new ObjectParameter("website", typeof(string));
    
            var photoParameter = photo != null ?
                new ObjectParameter("photo", photo) :
                new ObjectParameter("photo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_RegisterCompany", idParameter, naParameter, addParameter, emailParameter, phoneParameter, websiteParameter, photoParameter);
        }
    
        public virtual int sp_RegisterJobSeeker(Nullable<int> id, string na, Nullable<int> age, string add, string email, string phone, string qual, string gender, string state, string skill, string exp, string location, string photo)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var naParameter = na != null ?
                new ObjectParameter("na", na) :
                new ObjectParameter("na", typeof(string));
    
            var ageParameter = age.HasValue ?
                new ObjectParameter("age", age) :
                new ObjectParameter("age", typeof(int));
    
            var addParameter = add != null ?
                new ObjectParameter("add", add) :
                new ObjectParameter("add", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("Phone", phone) :
                new ObjectParameter("Phone", typeof(string));
    
            var qualParameter = qual != null ?
                new ObjectParameter("qual", qual) :
                new ObjectParameter("qual", typeof(string));
    
            var genderParameter = gender != null ?
                new ObjectParameter("gender", gender) :
                new ObjectParameter("gender", typeof(string));
    
            var stateParameter = state != null ?
                new ObjectParameter("state", state) :
                new ObjectParameter("state", typeof(string));
    
            var skillParameter = skill != null ?
                new ObjectParameter("skill", skill) :
                new ObjectParameter("skill", typeof(string));
    
            var expParameter = exp != null ?
                new ObjectParameter("exp", exp) :
                new ObjectParameter("exp", typeof(string));
    
            var locationParameter = location != null ?
                new ObjectParameter("location", location) :
                new ObjectParameter("location", typeof(string));
    
            var photoParameter = photo != null ?
                new ObjectParameter("photo", photo) :
                new ObjectParameter("photo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_RegisterJobSeeker", idParameter, naParameter, ageParameter, addParameter, emailParameter, phoneParameter, qualParameter, genderParameter, stateParameter, skillParameter, expParameter, locationParameter, photoParameter);
        }
    
        public virtual int sp_applycv(Nullable<int> cid, Nullable<int> jid, string cv, string applydate, string status)
        {
            var cidParameter = cid.HasValue ?
                new ObjectParameter("cid", cid) :
                new ObjectParameter("cid", typeof(int));
    
            var jidParameter = jid.HasValue ?
                new ObjectParameter("jid", jid) :
                new ObjectParameter("jid", typeof(int));
    
            var cvParameter = cv != null ?
                new ObjectParameter("cv", cv) :
                new ObjectParameter("cv", typeof(string));
    
            var applydateParameter = applydate != null ?
                new ObjectParameter("applydate", applydate) :
                new ObjectParameter("applydate", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_applycv", cidParameter, jidParameter, cvParameter, applydateParameter, statusParameter);
        }
    
        public virtual ObjectResult<sp_fetchAllJobDetails_Result> sp_fetchAllJobDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_fetchAllJobDetails_Result>("sp_fetchAllJobDetails");
        }
    
        public virtual int sp_Jobsearches(string qry)
        {
            var qryParameter = qry != null ?
                new ObjectParameter("qry", qry) :
                new ObjectParameter("qry", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Jobsearches", qryParameter);
        }
    }
}
