//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortalMVCApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_JobSeeker
    {
        public int U_Id { get; set; }
        public string U_Name { get; set; }
        public int U_Age { get; set; }
        public string U_Address { get; set; }
        public string U_Email { get; set; }
        public string U_Phone { get; set; }
        public string U_Qualification { get; set; }
        public string U_Gender { get; set; }
        public string U_State { get; set; }
        public string U_Skills { get; set; }
        public string U_Experience { get; set; }
        public string U_Location { get; set; }
        public string U_Photo { get; set; }
    }
}
