//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortalMVCApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AppliedJob
    {
        public int JobApplyId { get; set; }
        public int fk_JobId { get; set; }
        public int fk_UserId { get; set; }
        public string Resume { get; set; }
        public string ApplyDate { get; set; }
        public string Status { get; set; }
    }
}
