//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortalMVCApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Job
    {
        public int JobId { get; set; }
        public int fk_CompanyId { get; set; }
        public string JobTitle { get; set; }
        public string JobDescription { get; set; }
        public string Skills { get; set; }
        public string Experience { get; set; }
        public string SalaryRange { get; set; }
        public string Loction { get; set; }
        public string JobStatus { get; set; }
        public string ApplyLastDate { get; set; }
        public string PostedDate { get; set; }
    }
}
